---
- name: Add Kubernetes apt key
  ansible.builtin.shell: |
    curl -fsSL {{ kubernetes_repo_apt_key_url }} | gpg --dearmor -o /usr/share/keyrings/kubernetes-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Add Kubernetes apt repository
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] {{ kubernetes_repo_apt_url }} /
  register: kube_repo

- name: Update apt cache if repo changed
  apt:
    update_cache: true
  when: kube_repo is changed

- name: Install Kubernetes packages
  apt:
    name:
      - "kubelet={{ kubernetes_version }}"
      - "kubeadm={{ kubernetes_version }}"
      - "kubectl={{ kubernetes_version }}"
    state: present

- name: Hold Kubernetes packages at current version
  ansible.builtin.command: "apt-mark hold {{ item }}"
  loop:
    - kubelet
    - kubeadm
    - kubectl
  register: result
  changed_when: "'is already marked hold' not in result.stdout"

- name: Enable and start kubelet
  service:
    name: kubelet
    state: started
    enabled: true
