- name: Enable IPv4 forwarding natively
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Ensure nftables is running
  ansible.builtin.shell: |
    systemctl start nftables
    systemctl enable nftables

- name: Render nftables.conf
  ansible.builtin.template:
    src: templates/nftables.conf.j2
    dest: /etc/nftables.conf

- name: Check and apply nftables.conf
  ansible.builtin.shell: |
    nft -c -f /etc/nftables.conf
    nft -f /etc/nftables.conf