- name: Ensure proxmoxer is installed
  ansible.builtin.apt:
    name: python3-proxmoxer
    state: present

- name: Create a Proxmox VE Cluster
  community.proxmox.proxmox_cluster:
    state: present
    api_host: "{{ ansible_host }}"
    api_user: root@pam
    api_password: "{{ pve_root_password }}"
    api_timeout: 60
    validate_certs: false
    cluster_name: "{{ pve_cluster_name }}"

- name: Get cluster join information
  community.proxmox.proxmox_cluster_join_info:
    api_host: "{{ physical_subnet_prefix }}.1"
    api_user: root@pam
    api_password: "{{ pve_root_password }}"
    api_timeout: 60
    validate_certs: false
  register: cluster_info
  until: cluster_info.cluster_join is defined
  retries: -1
  delay: 10

- name: Set master ip address
  ansible.builtin.set_fact:
    master_ip_addr: "{{ physical_subnet_prefix }}.1"

- name: Set master fingeprint fact
  ansible.builtin.set_fact:
    master_fingerprint: "{{ cluster_info.cluster_join.nodelist | selectattr('pve_addr', 'equalto', master_ip_addr) | map(attribute='pve_fp') | first }}"

- block:
  - name: Join a Proxmox VE Cluster
    community.proxmox.proxmox_cluster:
      state: present
      api_host: "{{ item }}"
      api_user: root@pam
      api_password: "{{ pve_root_password }}"
      master_ip: "{{ physical_subnet_prefix }}.1"
      fingerprint: "{{ master_fingerprint }}"
      validate_certs: false
    register: join_result
    # It is until "join result is not changed" specificially, because in the current version of community.proxmox plugin,
    # it tends to misreport failed cluster joins as "changed". But if it is not "changed", and is not "failed" then it is 100% guranteeed that it has already
    # joined the cluster
    until: (join_result is not failed) and ((join_result is not changed) or ('Node already in the cluster.' in join_result.msg))
    retries: -1
    delay: 10
    with_inventory_hostnames:
        - all:pve_slaves