- name: SDN Setup
  hosts: pve_master
  roles:
    - role: sdn
      tags: sdn-configuration

- name: PVE Gateway Setup
  hosts: pve_nodes
  roles:
    - role: ha-gateway
      tags: ha-gateway

- name: Deploy CHR router
  hosts: pve_master
  roles:
    - role: mikrotik-chr-image-setup
    - role: chr-vm-config