- name: Make a folder for cloud images
  ansible.builtin.shell: >
    mkdir -p /tmp/cloud-images

- name: Download images
  ansible.builtin.get_url:
    url: "{{ item.dl_link }}"
    dest: /tmp/cloud-images/
  loop: "{{ cloud_images }}"
  register: dl_result

- name: Unzip if zipped
  ansible.builtin.shell: >
    unzip dl_result.dest -d /tmp/cloud-images/"{{ item.dl_link.split('/')[-1] }}"
  loop: "{{ dl_result }}"
  when: item.dest.endswith('.zip')

- name: Recursively find /tmp files older than 2 days
  ansible.builtin.find:
    paths: /tmp/cloud-images
    patterns: '*.img,*.raw,*.qcow2'
  register: image_files

- name: Create a blank vm for template
  ansible.builtin.shell: |
    qm create {{ 9000 + loop_index }} \
      --botdisk scsi0 \
      --cores 2 \
      --sockets 1 \
      --cpu cputype=host \
      --memory 2048 \
      --name {{ item.path.split('/')[-1] }} \
      --start 0 \
      --ostype l26
  loop: image_files.files

- name: Import the disk and attach the disk
  ansible.builtin.shell: |
    qm importdisk {{ 9000 + loop_index }} {{ item.path }} {{ template_storage }} \
    qm set {{ 9000 + loop_index }} --scsi0 {{ template_storage }}:vm-{{ 9000 + loop_index }}-disk-0
  loop: image_files.files


- name: Import the disk and attach the disk
  ansible.builtin.shell: |
    qm template {{ 9000 + loop_index }}
  loop: image_files.files

- name: Remove images
  ansible.builtin.shell: >
    rm -rf /tmp/cloud-images
  loop: dl_result