- name: Make a folder for cloud images
  ansible.builtin.shell: >
    mkdir -p /tmp/cloud-images

- name: Download images
  ansible.builtin.get_url:
    url: "{{ item.dl_link }}"
    dest: /tmp/cloud-images/{{ item.dl_link.split('/')[-1] }}
  loop: "{{ cloud_images }}"
  register: dl_result

- name: Unsure unzip is installed
  ansible.builtin.apt:
    name: unzip
    state: present
    update-cache: true

- name: Unzip if zipped
  ansible.builtin.shell: >
    unzip {{ item.dest }} -d /tmp/cloud-images/
  loop: "{{ dl_result.results }}"
  when: item.dest.endswith('.zip')

- name: Find all image files
  ansible.builtin.find:
    paths: /tmp/cloud-images
    patterns: '*.img,*.raw,*.qcow2'
  register: image_files

- name: Create a blank vm for template
  ansible.builtin.shell: |
    qm create {{ 9000 + ansible_loop.index }} \
      --cores 2 \
      --sockets 1 \
      --cpu cputype=host \
      --memory 2048 \
      --name {{ item.path.split('/')[-1] }} \
      --start 0 \
      --ostype l26
  loop: "{{ image_files.files }}"
  loop_control:
    extended: true

- name: Import the disk and attach the disk
  ansible.builtin.shell: |
    qm importdisk {{ 9000 + ansible_loop.index }} {{ item.path }} {{ template_storage }} \
    qm set {{ 9000 + ansible_loop.index }} --scsi0 {{ template_storage }}:vm-{{ 9000 + ansible_loop.index }}-disk-0
  loop: "{{ image_files.files }}"
  loop_control:
    extended: true


- name: Import the disk and attach the disk
  ansible.builtin.shell: |
    qm template {{ 9000 + ansible_loop.index }}
  loop: "{{ image_files.files }}"
  loop_control:
    extended: true

- name: Remove images
  ansible.builtin.shell: >
    rm -rf /tmp/cloud-images
  loop: "{{ dl_result }}"