- name: Ensure proxmoxer is installed
  ansible.builtin.apt:
    name: python3-proxmoxer
    state: present

- name: Create a Proxmox VE Cluster
  community.proxmox.proxmox_cluster:
    state: present
    api_host: pve01.noira.moe
    api_user: root@pam
    api_password: "{{ pve_root_password }}"
    validate_certs: false
    link0: 
    cluster_name: "noira-pve-cls"

- name: Get cluster join information
  community.proxmox.proxmox_cluster_join_info:
    api_host: 172.16.1.1
    api_user: root@pam
    api_password: "{{ pve_root_password }}"
    validate_certs: false
  register: cluster_info

- name: Set master fingeprint fact
  ansible.builtin.set_fact:
    master_fingerprint: "{{ cluster_info.cluster_join.nodelist | selectattr('pve_addr', 'equalto', '172.16.1.1') | map(attribute='pve_fp') | first }}"

- block:
  - name: Join a Proxmox VE Cluster
    community.proxmox.proxmox_cluster:
      state: present
      api_host: "{{ item }}"
      api_user: root@pam
      api_password: "{{ pve_root_password }}"
      master_ip: 172.16.1.1
      fingerprint: "{{ master_fingerprint }}"
    register: join_result
    until: not join_result.changed
    retries: 3
    delay: 10
    loop:
      - pve02.noira.moe
      - pve03.noira.moe
    
  - name: Mark failure if still reports changed
    ansible.builtin.fail:
      msg: "Cluster join might have failed for {{ item.item }}"
    loop: "{{ join_result.results | default([]) }}"
    when: item.changed