- name: Find out vnets bridge interfaces mac addresses
  ansible.builtin.shell: >
    qm config 1001 | awk '/net{{ vnet_index + 2 }}/ {print $2}' | sed 's/.*=\(.*\),.*/\1/'
  loop: "{{ vnets }}"
  register: vnet_macs
  loop_control:
    index_var: vnet_index

- name: Find out vmbr0 mac address
  ansible.builtin.shell: >
    qm config 1001 | awk '/net1/ {print $2}' | sed 's/.*=\(.*\),.*/\1/'
  register: vmbr0_mac

- name: Build configuration for mtu and interfaces ip addresses
  ansible.builtin.set_fact:
    cfg_ip_address_assignments: |
      #jinja2: lstrip_blocks: True
      {% for vnet in vnets %}
        {% set chr_if_mac = vnet_macs.results[loop.index0].stdout | upper %}
      interface set [/interface get [find mac-address="{{ chr_if_mac }}"] name] mtu=1340
      ip address add address={{ vnet.gateway }}/{{ vnet.mask }} interface=[/interface get [find mac-address="{{ chr_if_mac }}"] name]
      {% endfor %}

- name: Build configuration for ip interfaces address pools
  ansible.builtin.set_fact:
    cfg_ip_address_pools: |
      #jinja2: lstrip_blocks: True
      {% for vnet in vnets %}
      ip pool add ranges={{ vnet.dhcp_ranges }} name={{ vnet.name }}
      {% endfor %}

- name: Build configuration for interface dhcp server
  ansible.builtin.set_fact:
    cfg_dhcp_server: |
      #jinja2: lstrip_blocks: True
      {% for vnet in vnets %}
        {% set chr_if_mac = vnet_macs.results[loop.index0].stdout | upper %}
      ip dhcp-server network add address={{ vnet.cidr }} dns-server={{ vnet.gateway }} gateway={{ vnet.gateway }}
      ip dhcp-server add name={{ vnet.name }} interface=[/interface get [find mac-address="{{ chr_if_mac }}"] name] authoritative=yes address-pool={{ vnet.name }}
      {% endfor %}

- name: Build DROPALL rule
  ansible.builtin.set_fact:
    cfg_firewall_drop_all: |
      ip firewall filter add chain=forward action=drop comment="FORWARD DROP ALL"
      ip firewall filter add chain=input action=drop comment="INPUT DROP ALL"
      ip firewall filter add chain=forward action=accept src-address={{ physical_cidr }} dst-address={{ physical_cidr }} place-before=[/ip firewall filter find comment="FORWARD DROP ALL"] comment="FORWARD ACCEPT {{ physical_cidr }} <-> {{ physical_cidr }}"
      ip firewall filter add chain=input action=accept src-address={{ physical_cidr }} dst-address={{ physical_cidr }} place-before=[/ip firewall filter find comment="INPUT DROP ALL"] comment="INPUT ACCEPT {{ physical_cidr }} <-> {{ physical_cidr }}"
      
- name: Add Address List for LAN subnets
  ansible.builtin.set_fact:
    cfg_firewall_lan_address_list: |
      {% for vnet in vnets %}
      ip firewall address-list add list=lan address={{ vnet.cidr }}
      {% endfor %}
      ip firewall address-list add list=lan address={{ physical_cidr }}

- name: Rules for proper WAN functioning
  ansible.builtin.set_fact:
    cfg_firewall_allow_forward_to_fabric: |
      {% for vnet in vnets if vnet.allow_wan %}
      ip firewall filter add chain=forward action=accept src-address={{ vnet.cidr }} dst-address-list=!lan place-before=[/ip firewall filter find comment="FORWARD DROP ALL"] comment="FORWARD ACCEPT {{ vnet.name }} -> NOT LAN"
      ip firewall filter add chain=forward action=accept dst-address={{ vnet.cidr }} src-address-list=!lan place-before=[/ip firewall filter find comment="FORWARD DROP ALL"] comment="FORWARD ACCEPT NOT LAN -> {{ vnet.name }}"
      ip firewall filter add chain=input action=accept dst-address={{ vnet.cidr }} src-address-list=!lan place-before=[/ip firewall filter find comment="INPUT DROP ALL"] comment="INPUT ACCEPT {{ vnet.name }} -> LAN"
      ip firewall filter add chain=input action=accept src-address={{ vnet.cidr }} dst-address-list=!lan place-before=[/ip firewall filter find comment="INPUT DROP ALL"] comment="INPUT ACCEPT LAN -> {{ vnet.name }}"
      {% endfor %}
      ip firewall filter add chain=input action=accept src-address={{ physical_cidr }} dst-address-list=!lan place-before=[/ip firewall filter find comment="INPUT DROP ALL"] comment="INPUT ACCEPT NOT LAN -> {{ physical_cidr }}"
      ip firewall filter add chain=input action=accept dst-address={{ physical_cidr }} src-address-list=!lan place-before=[/ip firewall filter find comment="INPUT DROP ALL"] comment="INPUT ACCEPT {{ physical_cidr }} -> NOT LAN"
      
- name: Allow routing within subnets through the router
  ansible.builtin.set_fact:
    cfg_firewall_allow_subnet_inside_input: |
      {% for vnet in vnets %}
      ip firewall filter add chain=input action=accept dst-address={{ vnet.cidr }} src-address={{ vnet.cidr }} comment="INPUT ACCEPT INSIDE {{ vnet.name }}" place-before=[/ip firewall filter find comment="INPUT DROP ALL"]
      {% endfor %}

- name: Allow routing between vnets and physical subnet when allowed
  ansible.builtin.set_fact:
    cfg_firewall_allow_subnet_to_from_physical: |
      {% for vnet in vnets if vnet.route_to_physical_subnet %}
      ip firewall filter add chain=input action=accept dst-address={{ vnet.cidr }} src-address={{ physical_cidr }} comment="INPUT ACCEPT TO FROM PHYSICAL TO {{ vnet.name }}" place-before=[/ip firewall filter find comment="INPUT DROP ALL"]
      ip firewall filter add chain=input action=accept src-address={{ vnet.cidr }} dst-address={{ physical_cidr }} comment="INPUT ACCEPT TO TO PHYSICAL FROM {{ vnet.name }}" place-before=[/ip firewall filter find comment="INPUT DROP ALL"]
      ip firewall filter add chain=forward action=accept dst-address={{ vnet.cidr }} src-address={{ physical_cidr }} comment="INPUT ACCEPT TO FROM PHYSICAL TO {{ vnet.name }}" place-before=[/ip firewall filter find comment="FORWARD DROP ALL"]
      ip firewall filter add chain=forward action=accept src-address={{ vnet.cidr }} dst-address={{ physical_cidr }} comment="INPUT ACCEPT TO TO PHYSICAL FROM {{ vnet.name }}" place-before=[/ip firewall filter find comment="FORWARD DROP ALL"]
      {% endfor %} 

- name: Build configuration for inter-subnet routing
  ansible.builtin.set_fact:
    cfg_firewall_subnet_forward: |
      #jinja2: lstrip_blocks: True
      {% for vnet in vnets %}
        {% if vnet.allowed_routes is defined %}
          {% for allow_route_vnet in vnets if allow_route_vnet.name in vnet.allowed_routes %}
      ip firewall filter add chain=forward action=accept src-address={{ vnet.cidr }} dst-address={{ allow_route_vnet.gateway }} protocol=tcp comment="TCP Rule for VNets {{ vnet.name }} -> {{ allow_route_vnet.name }}" place-before=[/ip firewall filter find comment="FORWARD DROP ALL"]
      ip firewall filter add chain=forward action=accept src-address={{ allow_route_vnet.cidr }} dst-address={{ vnet.gateway }} protocol=tcp comment="TCP Rule for VNets {{ allow_route_vnet.name }} -> {{ vnet.name }}" place-before=[/ip firewall filter find comment="FORWARD DROP ALL"]
      ip firewall filter add chain=forward action=accept src-address={{ vnet.cidr }} dst-address={{ allow_route_vnet.gateway }} protocol=udp comment="UDP Rule for VNets {{ vnet.name }} -> {{ allow_route_vnet.name }}" place-before=[/ip firewall filter find comment="FORWARD DROP ALL"]
      ip firewall filter add chain=forward action=accept src-address={{ allow_route_vnet.cidr }} dst-address={{ vnet.gateway }} protocol=udp comment="UDP Rule for VNets {{ allow_route_vnet.name }} -> {{ vnet.name }}" place-before=[/ip firewall filter find comment="FORWARD DROP ALL"]
          {% endfor %}
        {% endif %}
      {% endfor %}

- name: Build configuration for src-nat
  ansible.builtin.set_fact:
    cfg_src_nat: |
      #jinja2: lstrip_blocks: True
      {% for vnet in vnets %}
        {% set chr_if_mac = vnet_macs.results[loop.index0].stdout | upper %}
        {% if vnet.allow_wan %}
      ip firewall nat add chain=srcnat in-interface=[/interface get [find mac-address="{{ chr_if_mac }}"] name] out-interface=[/interface get [find mac-address="{{ vmbr0_mac.stdout | upper }}"] name] action=masquerade
        {% endif %}
      {% endfor %}

- name: Build configuration for dns server
  ansible.builtin.set_fact:
    cfg_dns: |
      #jinja2: lstrip_blocks: True
      ip dns set servers=1.1.1.1,8.8.8.8 allow-remote-requests=yes

- name: Wait for CHR to be reachable via ssh
  ansible.builtin.wait_for:
    host: "{{ vmbr0_chr_ip }}"
    port: 22
    delay: 2
    timeout: 300
    state: started

- name: Execute main configuration on CHR
  ansible.builtin.shell: |
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null admin@{{ vmbr0_chr_ip }} << 'EOF'
    {{ cfg_ip_address_assignments }}
    {{ cfg_ip_address_pools }}
    {{ cfg_dhcp_server }}
    {{ cfg_dns }}
    {{ cfg_firewall_drop_all }}
    {{ cfg_firewall_allow_subnet_inside_input }}
    {{ cfg_firewall_allow_subnet_to_from_physical }}
    {{ cfg_firewall_lan_address_list }}
    {{ cfg_firewall_subnet_forward }}
    {{ cfg_firewall_allow_forward_to_fabric }}
    {{ cfg_src_nat }}
    EOF

- name: Block torrent ports
  ansible.builtin.set_fact:
    cfg_ports_torrent_block: |
      #jinja2: lstrip_blocks: True
      ip firewall filter add chain=forward action=drop src-address={{ physical_cidr }} protocol=tcp dst-port=6881-6889
      ip firewall filter add chain=forward action=drop src-address={{ physical_cidr }} protocol=udp dst-port=6881-6889
      ip firewall filter add chain=forward action=drop src-address={{ physical_cidr }} protocol=tcp dst-port=4321
      ip firewall filter add chain=forward action=drop src-address={{ physical_cidr }} protocol=tcp dst-port=3544
      ip firewall filter add chain=forward action=drop src-address={{ physical_cidr }} protocol=udp dst-port=4321
      ip firewall filter add chain=forward action=drop src-address={{ physical_cidr }} protocol=udp dst-port=3544
  when: block_torrents

- name: Create layer7 filtering rules
  ansible.builtin.set_fact: 
    cfg_layer7_torrent_block: |
      ip firewall layer7-protocol add name=torrentdomains regexp="^.*(get|GET).+(torrent|thepiratebay|isohunt|entertane|demonoid|btjunkie|mininova|flixflux|torrentz|vertor|h33t|btscene|bitunity|bittoxic|thunderbytes|entertane|zoozle|vcdq|bitnova|bitsoup|meganova|fulldls|btbot|flixflux|seedpeer|fenopy|gpirate|commonbits).*"
      add chain=forward src-address={{ physical_cidr }} layer7-protocol=torrents action=drop comment=torrents
  when: block_torrents

- name: Execute torrent blocking configuration on CHR
  ansible.builtin.shell: |
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null admin@{{ vmbr0_chr_ip }} << 'EOF'
    {{ item }}
    EOF
  loop:
    - "{{ cfg_layer7_torrent_block }}"
    - "{{ cfg_ports_torrent_block }}"
  when: block_torrents

- name: Set CHR admin password
  ansible.builtin.shell: >
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null admin@{{ vmbr0_chr_ip }} user set admin password={{ chr_admin_password }}

# - name: Add CHR admin public key
#   ansible.builtin.shell: >
#     ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null admin@{{ vmbr0_chr_ip }} /file print file=tmpkey; /file set tmpkey.txt contents="{{ chr_admin_public_key }}"; /user ssh-keys import public-key-file=tmpkey.txt user=admin; /file remove tmpkey.txt 
#     ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null admin@{{ vmbr0_chr_ip }} /ip ssh set always-allow-password-login=no