- name: Make a folder for cloud images
  tags: template-creation
  ansible.builtin.shell: >
    mkdir -p /tmp/cloud-images

- name: Download images
  tags: template-creation
  ansible.builtin.get_url:
    url: "{{ item.dl_link }}"
    dest: /tmp/cloud-images/{{ item.dl_link.split('/')[-1] }}
    timeout: 360
  loop: "{{ cloud_images }}"
  register: dl_result

- name: Unsure unzip is installed
  tags: template-creation
  ansible.builtin.apt:
    name: unzip
    state: present
    update-cache: true

- name: Unzip if zipped
  tags: template-creation
  ansible.builtin.shell: >
    unzip -o {{ item.dest }} -d /tmp/cloud-images/
  loop: "{{ dl_result.results }}"
  when: item.dest.endswith('.zip')

- name: Find all image files
  tags: template-creation
  ansible.builtin.find:
    paths: /tmp/cloud-images
    patterns: '*.img,*.raw,*.qcow2'
  register: image_files

- name: Retreive pve api user
  delegate_to: localhost
  ansible.builtin.shell: |
    awk '/api-user/{print $2}' ../../../credentials.yml
  register: pve_user_command_result

- name: Retreive pve api user token secret
  delegate_to: localhost
  ansible.builtin.shell: |
    awk '/api-token/{print $2}' ../../../credentials.yml
  register: pve_secret_command_result

- name: Set fact for pve api user
  ansible.builtin.set_fact:
    pve_user: '{{ pve_user_command_result.stdout }}'

- name: Set fact for pve api secret
  ansible.builtin.set_fact:
    pve_secret: '{{ pve_secret_command_result.stdout }}'

- name: Create new VMs
  community.proxmox.proxmox_kvm:
    api_host: "{{ groups['pve_master'][0].split('.')[0] }}"
    api_user: "{{ pve_user }}"
    api_token_id: "automation"
    api_token_secret: "{{ pve_secret }}"
    vmid: "{{ 9000 + ansible_loop.index }}" 
    name: "{{ item.path.split('/')[-1] | replace('_', '-') }}"
    node: "{{ groups['pve_master'][0].split('.')[0] }}"
    cores: 2
    memory: 2048
    cpu: "host"
    scsihw: "virtio-scsi-pci"
    ostype: "l26"
    state: present
    boot: order=scsi0;net0
    ide:
      ide2: "local-zfs-pool:cloudinit"
    ciuser: "root"
    cipassword: "password"
    net: 
      net0: virtio,bridge=vmbr0
    description: |
      "Ansible generated cloud template, made from {{ item.path.split('/')[-1] | replace('_', '-') }} image."
  loop: "{{ image_files.files }}"
  loop_control:
    extended: true

- name: Check if disks are already imported
  ansible.builtin.shell: |
    qm config {{ 9000 + ansible_loop.index }}
  loop: "{{ image_files.files }}"
  loop_control:
    extended: true
  register: qm_config_results

- name: Import the disk and attach the disk
  tags: template-creation
  ansible.builtin.shell: |
    qm importdisk {{ 9000 + ansible_loop.index }} {{ item.path }} local-zfs-pool
  loop: "{{ image_files.files }}"
  loop_control:
    extended: true
  when: "{{ 'disk-0' not in qm_config_results.results | selectattr('item', 'equalto', item) | map(attribute='stdout') | string }}"

- name: Attach disks properly
  community.proxmox.proxmox_kvm:
    api_host: "{{ groups['pve_master'][0].split('.')[0] }}"
    api_user: "{{ pve_user }}"
    api_token_id: "automation"
    api_token_secret: "{{ pve_secret }}"
    node: "{{ groups['pve_master'][0].split('.')[0] }}"
    vmid: "{{ 9000 + ansible_loop.index }}" 
    update: true
    update_unsafe: true
    scsi: 
      scsi0: "local-zfs-pool:vm-{{ 9000 + ansible_loop.index }}-disk-0,discard=on"
  loop: "{{ image_files.files }}"
  loop_control:
    extended: true
  when: "{{ 'scsi0: local-zfs-pool' not in qm_config_results.results | selectattr('item', 'equalto', item) | map(attribute='stdout') | string }}"

- name: Convert vms to templates
  community.proxmox.proxmox_kvm:
    api_host: "{{ groups['pve_master'][0].split('.')[0] }}"
    api_user: "{{ pve_user }}"
    api_token_id: "automation"
    api_token_secret: "{{ pve_secret }}"
    vmid: "{{ 9000 + ansible_loop.index }}" 
    state: template
  loop: "{{ image_files.files }}"
  loop_control:
    extended: true

- include_tasks: clone-vm.yml
  loop: "{{ image_files.files }}"
  loop_control:
    loop_var: image
    index_var: image_index

- include_tasks: migrate-vm.yml
  loop: "{{ image_files.files }}"
  loop_control:
    loop_var: image
    index_var: image_index

- include_tasks: template-vm.yml
  loop: "{{ image_files.files }}"
  loop_control:
    loop_var: image
    index_var: image_index

# - name: Remove images
#   ansible.builtin.shell: >
#     rm -rf /tmp/cloud-images

