# According to https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_13_Trixie

- name: Ensure correct /etc/hosts
  ansible.builtin.template:
    src: templates/hosts.j2
    dest: /etc/hosts

- name: Prerequisite for debian 13 specific ansible module working
  ansible.builtin.apt:
    state: present
    name: python3-debian

- name: Add PVE repository for Debian Trixie
  ansible.builtin.deb822_repository:
    name: PVE_Trixie_Repo
    types: [deb]
    uris: http://download.proxmox.com/debian/pve
    suites: [trixie]
    components: [pve-no-subscription]
    signed_by: /usr/share/keyrings/proxmox-archive-keyring.gpg
    state: present
    enabled: true

- name: Add the Proxmox VE repository keyring
  ansible.builtin.shell: |
    wget https://enterprise.proxmox.com/debian/proxmox-archive-keyring-trixie.gpg -O /usr/share/keyrings/proxmox-archive-keyring.gpg

- name: Set GRUB device selections
  ansible.builtin.debconf:
    name: grub-pc
    question: grub-pc/install_devices
    value: 
      - /dev/nvme0n1
      - /dev/nvme1n1
    vtype: multiselect

- name: Install grub-pc non-interactively
  ansible.builtin.apt:
    name: grub-pc
    state: latest
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Run apt update and apt upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe

- name: Install the Proxmox VE Kernel, Proxmox VE Packages
  ansible.builtin.apt:
    state: present
    name:
      - proxmox-default-kernel
      - proxmox-ve
      - postfix
      - open-iscsi
      - chrony

- name: Remove Debian Kernel
  ansible.builtin.shell: >
    apt remove linux-image-amd64 'linux-image-6.12*' ; update-grub ; apt remove os-prober

- name: Reboot
  ansible.builtin.reboot:
    reboot_timeout: 3600