---
- name: Install Required Packages
  apt:
  - name:
    - keepalived
    - haproxy
  state: present

- name: Allow binding to non-existent iptables
  ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    state: present
    reload: yes

- name: Render Keepalived Config
  ansible.builtin.template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: Render Haproxy Config
  ansible.builtin.template:
    src: templates/keepalived.conf.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Enable and Start Services
  ansible.builtin.shell: |
    "systemctl enable keepalived haproxy && systemctl restart keepalived haproxy"