---
- name: Install Required Packages
  ansible.builtin.apt:
    name:
      - keepalived
      - haproxy
  state: present

- name: Allow binding to non-existent IPs
  ansible.posix.sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    state: present
    reload: yes

- name: Render Keepalived Config
  ansible.builtin.template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: Render Haproxy Config
  ansible.builtin.template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Enable and Start keepalived
  ansible.builtin.service:
    name: keepalived
    enabled: yes
    state: restarted


- name: Enable and Start keepalived
  ansible.builtin.service:
    name: haproxy
    enabled: yes
    state: restarted