- name: Overwrite system disk with zeroes
  tags: partitioning
  ansible.builtin.shell: > 
    dd if=/dev/zero of=/dev/md0 bs=1M count=513 status=progress

- name: Create system partition
  community.general.parted:
    device: /dev/md0
    label: msdos
    number: 1
    part_start: 1GiB
    part_end: 56GiB
    state: present

- name: Create swap partition
  community.general.parted:
    device: /dev/md0
    number: 2
    part_start: 56GiB
    part_end: 100%
    state: present

- name: Format partitions
  ansible.builtin.shell: >
    mkfs.ext4 /dev/md0p1 && mkswap /dev/md0p2

- name: Mount debootstrap directory
  ansible.builtin.shell: >
    mount /dev/md0p1 /mnt

# Courtesy of https://quantum5.ca/2024/08/12/installing-debian-proxmox-by-hand-from-rescue-environment/
- name: Run debootstrap
  tags: debootstrap
  ansible.builtin.shell: >
    debootstrap --arch amd64 bookworm /mnt http://deb.debian.org/debian

# Courtesy of https://quantum5.ca/2024/08/12/installing-debian-proxmox-by-hand-from-rescue-environment/
- name: Add repositories
  ansible.builtin.copy:
    dest: /mnt/etc/apt/sources.list
    content: |
      deb http://deb.debian.org/debian bookworm main non-free-firmware
      deb-src http://deb.debian.org/debian bookworm main non-free-firmware

      deb http://security.debian.org/debian-security bookworm-security main non-free-firmware
      deb-src http://security.debian.org/debian-security bookworm-security main non-free-firmware

      # bookworm-updates, to get updates before a point release is made;
      # see https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_updates_and_backports
      deb http://deb.debian.org/debian bookworm-updates main non-free-firmware
      deb-src http://deb.debian.org/debian bookworm-updates main non-free-firmware

- name: Create routing table for vSwitch
  ansible.builtin.shell: >
    echo "1 vswitch" >> /mnt/etc/iproute2/rt_tables

# With vSwitch upstream support https://docs.hetzner.com/robot/dedicated-server/network/vswitch/
- name: Configure networking
  ansible.builtin.copy:
    dest: /mnt/etc/network/interfaces
    content: |
      auto enp0s31f6.4090
      iface enp0s31f6.4090 inet static
        address 172.16.1."{{ groups['pve_nodes'].index(inventory_hostname) + 1 }}"
        netmask 255.255.0.0
        vlan-draw-device enp0s31f6
        mtu 1400
        # ipv4 public subnet
        up ip addr add {{ ansible_host }}/26 dev enp0s31f6.4000
        up ip rule add from {{ ansible_host }} lookup vswitch
        up ip rule add to {{ ansible_host }} lookup vswitch
        up ip route add default via {{ ansible_host }} dev enp0s31f6.4000 table vswitch
        down ip addr del {{ ansible_host }}/26 dev enp0s31f6.4000
        down ip route del default via {{ ansible_host }} dev enp0s31f6.4000 table vswitch
        down ip rule del to {{ ansible_host }} lookup vswitch
        down ip rule del from {{ ansible_host }} lookup vswitch
      
      auto br0
      iface br0 inet static
        bridge_ports enp0s31f6.4090
        bridge_stp off
        bridge_fd 0

# With vSwitch upstream support https://docs.hetzner.com/robot/dedicated-server/network/vswitch/
- name: Configure resolv.conf
  ansible.builtin.copy:
    dest: /mnt/etc/network/interfaces
    content: |
      nameserver 1.1.1.1
      nameserver 8.8.8.8


- name: Bind virtual filesystems
  ansible.posix.mount:
    path: "/mnt/{{ item }}"
    src: "/{{ item }}"
    fstype: bind
    opts: bind
    state: mounted
  loop: [proc, sys, dev, dev/pts, run]

- name: Update package index inside chroot
  ansible.builtin.shell: >
    chroot /mnt apt update

- name: Install needed packages
  ansible.builtin.shell: >
    chroot /mnt DEBIAN_FRONTEND=noninteractive apt install -y linux-image-amd64 grub-pc wget lvm2 openssh-server mdadm

