- name: Stop all arrays
  tags: fresh-start
  ansible.builtin.shell: mdadm --stop --scan

- name: Overwrite disks with zeroes
  tags: fresh-start
  ansible.builtin.shell: dd if=/dev/zero of={{ item }} bs=1M count=256 status=progress
  loop:
    - /dev/nvme0n1
    - /dev/nvme1n1

- name: Create system partitions
  community.general.parted:
    device: "{{ item }}"
    number: 1
    state: present
    part_start: 1GiB
    part_end: 64GiB
  loop:
    - /dev/nvme0n1
    - /dev/nvme1n1

- name: Create local-lvm partitions
  community.general.parted:
    device: "{{ item }}"
    number: 2
    state: present
    part_start: 64GiB
    part_end: 60%
  loop:
    - /dev/nvme0n1
    - /dev/nvme1n1

- name: Create longhorn partitions
  community.general.parted:
    device: "{{ item }}"
    number: 3
    state: present
    part_start: 60%
    part_end: 85%
  loop:
    - /dev/nvme0n1
    - /dev/nvme1n1

- name: Create linstor partitions
  community.general.parted:
    device: "{{ item }}"
    number: 4
    state: present
    part_start: 85%
    part_end: 100%
  loop:
    - /dev/nvme0n1
    - /dev/nvme1n1

- name: Zero all superblocks from component disks
  ansible.builtin.shell: >
    mdadm --zero-superblock /dev/nvme0n1p1 /dev/nvme1n1p1 /dev/nvme0n1p2 /dev/nvme1n1p2 /dev/nvme0n1p3 /dev/nvme1n1p3 /dev/nvme0n1p4 /dev/nvme1n1p4

- name: Create system software raid device
  ansible.builtin.shell: >
    mdadm --create /dev/md0 --level=1 --raid-devices=2 /dev/nvme0n1p1 /dev/nvme1n1p1 --metadata=0.90

- name: Create local-lvm software raid device
  ansible.builtin.shell: >
    yes | mdadm --create /dev/md1 --level=0 --raid-devices=2 /dev/nvme0n1p2 /dev/nvme1n1p2

- name: Create longhorn software raid device
  ansible.builtin.shell: >
    yes | mdadm --create /dev/md2 --level=0 --raid-devices=2 /dev/nvme0n1p3 /dev/nvme1n1p3

- name: Create linstor software raid device
  ansible.builtin.shell: >
    yes | mdadm --create /dev/md3 --level=0 --raid-devices=2 /dev/nvme0n1p4 /dev/nvme1n1p4