- name: Build commands for all ports for CHR router
  ansible.builtin.set_fact:
    port_if_add_commands: |
      qm set 1001 -net1 virtio,bridge=vmbr0
      {% for vnet in vnets %}
      qm set 1001 -net{{ loop.index + 1 }} virtio,bridge={{ vnet.name }}
      {% endfor %}

- name: Set CHR ports
  ansible.builtin.shell: >
    {{ port_if_add_commands }}

- name: Set up hourly replication to other nodes via zfs
  failed_when: false # DEBUG
  ansible.builtin.set_fact:
    pvesr_job_commands: |
      {% set ns = namespace(pve_nodes = [], vmids = []) %}
      {% for i in range(2, (groups['pve_nodes'] | length) + 1) %}
      {% set ns.pve_nodes = ns.pve_nodes + ["pve0" ~ i] %}
      {% endfor %}
      {% for node in ns.pve_nodes %}
      pvesr create-local-job 1001-{{ loop.index }} {{ node }} --schedule "*/15" --rate 500
      pvesr schedule-now 1001-{{ loop.index }}
      {% endfor %}

- name: Run ZFS job commands
  failed_when: false # DEBUG
  ansible.builtin.shell: |
    {{ pvesr_job_commands }}

- name: Add VM to HA
  tags: chr_ha
  ansible.builtin.shell: |
    ha-manager add vm:1001 --failback 0