- name: Build a list of all zfs partitions
  ansible.builtin.set_fact:
    all_zfs_partitions: >-
      {{
        blockdevs
        | product([2])
        | map('join', 'p')
        | join(' ')
      }}

- name: Create basic non-redundant pool for vm disks and add it to PVE
  ansible.builtin.shell: |
    zpool create local-zfs-pool -f {{ zfs_pool_settings }} mirror {{ all_zfs_partitions }}
    pvesm add zfspool local-zvs-pool -pool local-zfs-pool