- name: Clean up binds
  tags: partitioning
  ansible.builtin.shell: >
    umount -l /mnt/{{ item }}
  loop: [proc, sys, dev, dev/pts, run]
  failed_when: false

- name: Clean up root mount
  tags: partitioning
  ansible.posix.mount:
    path: "/mnt"
    state: unmounted

- name: Stop all arrays
  ansible.builtin.shell: mdadm --stop --scan

- name: Overwrite disks with zeroes
  tags: fresh-start
  ansible.builtin.shell: dd if=/dev/zero of={{ item }} bs=1M count=256 status=progress
  loop: "{{ blockdevs }}"

- name: Create md array component partitions for base system 
  community.general.parted:
    device: "{{ item }}"
    number: 1
    label: msdos
    state: present
    part_start: 1GiB
    part_end: "{{ pve_system_disk_size }}"
  loop: "{{ blockdevs }}"

- name: Create component partitions for local vm disks
  community.general.parted:
    device: "{{ item }}"
    number: 2
    state: present
    part_start: "{{ pve_system_disk_size }}"
    part_end: "{{ local_zfs_vmdata_disk_allocation_end }}"
  loop: "{{ blockdevs }}"

- name: Create component partitions for longhorn
  community.general.parted:
    device: "{{ item }}"
    number: 3
    state: present
    part_start: "{{ local_zfs_vmdata_disk_allocation_end }}"
    part_end: "{{ longhorn_disk_allocation_end }}"
  loop: "{{ blockdevs }}"

- name: Create component partitions for linstor
  community.general.parted:
    device: "{{ item }}"
    number: 4
    state: present
    part_start: "{{ longhorn_disk_allocation_end }}"
    part_end: "{{ linstor_disk_allocation_end }}"
  loop: "{{ blockdevs }}"

- name: Build a list of all partitions
  ansible.builtin.set_fact:
    all_blockdev_partitions: >-
      {{
        blockdevs
        | product(range(1,4))
        | map('join', 'p')
        | join(' ')
      }}

- name: Zero all superblocks from component disks
  ansible.builtin.shell: >
    mdadm --zero-superblock {{ all_blockdev_partitions }}

- name: Wipefs from all partitions just in case
  ansible.builtin.shell: >
    wipefs --all --force {{ all_blockdev_partitions }}

- name: Build a list of all system partitions
  ansible.builtin.set_fact:
    all_system_partitions: >-
      {{
        blockdevs
        | product([1])
        | map('join', 'p')
        | join(' ')
      }}

- name: Create md array for linux base system
  ansible.builtin.shell: >
    mdadm --create /dev/md0 --level=1 --raid-devices={{ len(blockdevs) }} {{ all_system_partitions }} --metadata=0.90 --name=pve-system

