# Reference: https://linbit.com/blog/linstor-setup-proxmox-ve-volumes/

---
- name: Install headers for the current kernel
  ansible.builtin.apt:
    name: "linux-headers-{{ ansible_kernel }}"
    state: present
    update_cache: yes

- name: Install drbd, compile module for the current kernel
  ansible.builtin.apt:
    name:
      - drbd-dkms
      - drbd-utils

- name: Unload drbd kernel module
  community.general.modprobe:
    name: drbd
    state: absent

- name: Load drbd kernel module
  community.general.modprobe:
    name: drbd
    state: present
    persistent: yes

- name: Install linstor satellite
  ansible.builtin.apt:
    name:
      - linstor-satellite
      - linstor-client

- name: Enable linstor satellite service
  ansible.builtin.service:
    name: linstor-satellite
    enabled: true

- name: Reboot node
  ansible.builtin.reboot:
    reboot_timeout: 600

- name: Check that drbd9 is present. Fail if drbd8 is loaded
  ansible.builtin.shell: "modinfo drbd | grep ^version"
  register: drbd9_module_ver
  failed_when: drbd9_module_ver.stdout.startswith('8.')

- name: Add nodes on the controller
  ansible.builtin.shell: 'ssh root@{{ linstor_controller }} "linstor node create {{ inventory_hostname }} {{ ansible_hostname }}"'