nft_dnat_mappings:
- name: SSH_BASTION
  src_port: 10022
  dest_ip: 172.16.149.154
  dest_port: 22

- name: SSH_SANYA_BASTION
  src_port: 10023
  dest_ip: 172.16.0.133
  dest_port: 22

vrouter_id: "75"
edge_fw_virtual_ip: "172.16.0.200"