- name: Create an automation user
  ansible.builtin.shell: |
    pveum user add {{ api_automation_user }}@pve --password "{{ automation_user_pass }}"
    pveum acl modify / --user {{ api_automation_user }}@pve --roles PVEAdmin
    
- name: Generate token for automation user
  ansible.builtin.shell: >
    pveum user token add {{ api_automation_user }}@pve automation --privsep 0 | awk '/value/ && NR > 2 {print $4}'
  register: token_generation_result

- name: Ensure the global data file exists
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ lookup('env', 'PWD') }}/credentials.yml"
    state: touch
    mode: '0644'

- name: Update a specific setting
  delegate_to: localhost
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'PWD') }}/credentials.yml"
    regexp: '^api-token: '
    line: 'api-token: {{ token_generation_result.stdout }}'
    state: present

- name: Update a specific setting
  delegate_to: localhost
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'PWD') }}/credentials.yml"
    regexp: '^api-user: '
    line: "api-user: {{ api_automation_user }}"
    state: present