- name: Ensure exit bridge definition is in /etc/network/interfaces
  ansible.builtin.blockinfile:
    path: /etc/network/interfaces
    block: |
      auto vmbr-exit
      iface vmbr-exit inet static
        address 10.255.255.254/32
        bridge_ports none
        bridge-stp off
        bridge-fd 0
        mtu 1400
        bridge_maxwait 0
    state: present
    create: yes

- name: Reboot networking
  ansible.builtin.shell: |
    systemctl restart networking