---
- Generic k8s host setup
  hosts: all
  become: true

  tasks:
    - name: Disable swap
      command: swapoff -all
      when: ansible_swaptotal_mb > 0

    - name: Remove swap from fstab
      repalce:
        path: /etc/fstab
        regeexp: '^\s*[^#]\S*\s+swap\s+'
        replace: '# \g<0>'

    - name: Install base packages
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - gnupg
        state: present
        update_cache: true

    - name: Set sysctl for Kubernetes networking
      copy:
        dest: /etc/sysctl.d/99-kubernetes.conf
        content: |
          net.bridge.bridge-nf-call-iptables=1
          net.ipv4.ip_forward=1
      notify: Reload sysctl

    handlers:
      - name: Reload sysctl
        command: sysctl --system