- name: Prepare all Kubernetes nodes
  hosts: kubernetes
  become: true
  roles:
    - prepare-nodes
    - container-runtime
    - kubernetes-install

- name: Initialize the first control plane node
  hosts: kube_control_plane[0]
  become: true
  roles:
    - cluster-init

- name: Join other control plane nodes
  hosts: "kube_control_plane[1:]"
  become: true
  roles:
    - control-plane-join

- name: Join worker nodes to the cluster
  hosts: kube_node
  become: true
  roles:
    - worker-join
